### ISSUE TITLE
Ability to seat upcoming party by clicking on table

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#11]
Our third prototype had a dropdown that defaulted to "Walk In" but could be used to select "Upcoming"

![image](https://cloud.githubusercontent.com/assets/18295616/14299678/d5b9c488-fb59-11e5-98f8-52c7ebdf4e41.png)

**Comment by abartow** [comment]
Done as of https://github.com/ZackUhlenhuth/HostHelper/commit/d464739644619aa624a0c573dd855c5d7804b967
