### ISSUE TITLE
Servers' area overlays should note their usage and capacity

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#13]
![image](https://cloud.githubusercontent.com/assets/18295616/14299775/677b22ae-fb5a-11e5-941f-a29ee443eade.png)

**Comment by abartow** [comment]
Done as of https://github.com/ZackUhlenhuth/HostHelper/commit/1a9d05a7667c587cabf247985b79ba0cab7e61ef
