### ISSUE TITLE
Table capacities should be full if table is grayed out

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#14]
![image](https://cloud.githubusercontent.com/assets/18295616/14299985/9e25b1d8-fb5b-11e5-93ac-843e84dc6227.png)

**Comment by abartow** [comment]
I'm not sure this is an issue anymore?

**Comment by jameshloving** [comment]
FYI I'm balls deep in a field exercise right  now and have limited comms
and no ability to Code before Monday

**Comment by nickuhlenhuth** [comment]
Not an issue
