### ISSUE TITLE
Insufficient padding between reservation labels and fields

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#2]
![selection_001](https://cloud.githubusercontent.com/assets/18295616/14299379/1a0276be-fb58-11e5-9e3e-8c80849a2f6c.png)

**Comment by abartow** [comment]
Should be fixed by https://github.com/ZackUhlenhuth/HostHelper/commit/796945ce4773f22160a760eec38afba22dd72b18
