### ISSUE TITLE
Reservations on Upcoming List should also display Date

### ISSUE THREAD

**Issue by ZackUhlenhuth** [ZackUhlenhuth/HostHelper#20]
right now it only displays the time

**Comment by ZackUhlenhuth** [comment]
don't really need to do this anymore since we only show those for the next 12 hours and anything expired will have an urgent notification

**Comment by jameshloving** [comment]
I think we still need to have a date viewing functionality, given the scenario of a reservation made for a later date, e.g., Valentine's.

**Comment by jameshloving** [comment]
Nevermind, this would be on the "far away Upcoming" list.
