### ISSUE TITLE
SeatMap needs to be more detailed

### ISSUE THREAD

**Issue by ZackUhlenhuth** [ZackUhlenhuth/HostHelper#21]
more tables and tables of varying sizes

**Comment by abartow** [comment]
I added some more tables so we can complete our tasks for our user testing.

https://github.com/ZackUhlenhuth/HostHelper/commit/fce3cb18f2e159ccd4b2df617c61b11b23c887ca

**Comment by jameshloving** [comment]
We still need to have varying table sizes (and I think the images should be reflective of the actual table size)

I'll take a crack at that this evening

**Comment by jameshloving** [comment]
Changed up the default table capacity, added dynamic table sizing based on table capacity, and added support for vertical tables in a85c27a75692ecc42115a48a89043c7567abf3cc
