### ISSUE TITLE
Need support for multi-table seatings

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#23]
We talked about this in our paper prototyping stages: If a party that's too large for any one current table is being seated, the system can suggest combinations of tables that will seat the party.

Barring any backend support from the algorithm, we should at least allow for the user to create multi-table parties.

...but it's a huge addition, I think, code-wise.

**Comment by abartow** [comment]
I'm not sure it's a huge addition, just so long as we don't try and suggest table pairs. You can just set many tables to have the same party in the model, and the rest of the code should be most correct to do what we want. It's just a matter of what we want for an interface.

**Comment by abartow** [comment]
To do if we get around to it.

**Comment by abartow** [comment]
I spoke with a TA and it seems pretty safe to me to just leave this feature out.

**Comment by ZackUhlenhuth** [comment]
I'm closing this
