### ISSUE TITLE
Have an upcoming list page for upcoming entries that are far away

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#28]

**Comment by nickuhlenhuth** [comment]
I've almost finished this for you. I think the only remaining step is to turn the "Future Reservations" button into a "Hide Future Reservations" button, so that you can close the popup

**Comment by abartow** [comment]
This is just my opinion, but I think we've got a bit too much view creeping into our model with the way this is currently implemented.

**Comment by abartow** [comment]
I think I've finished this up as of https://github.com/ZackUhlenhuth/HostHelper/commit/311b0c5ff7e25470b0b2c72aa14e7693028ffcda, as it was blocking some of my other tasks. I think it might be slightly different than what you had in mind, so if you'd like me to make changes, just let me know.
