### ISSUE TITLE
Insufficient padding between "Add to Waitlist" labels and fields

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#3]
![selection_002](https://cloud.githubusercontent.com/assets/18295616/14299401/39315dde-fb58-11e5-9411-f1a4612705a2.png)

**Comment by abartow** [comment]
Should be fixed by https://github.com/ZackUhlenhuth/HostHelper/commit/1a6906aa1734692663cc0c924cd432f6613b70f3
