### ISSUE TITLE
User ability to zoom in should be limited

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#32]

**Comment by abartow** [comment]
https://github.com/ZackUhlenhuth/HostHelper/commit/68218d8499bd7c0ed343164fcabe4f14177b2c2e limits user ability to zoom. Is this what you want?

**Comment by jameshloving** [comment]
68218d8499bd7c0ed343164fcabe4f14177b2c2e limits the ability to zoom out. The feedback we got was about excessive zooming in - so a table takes up the entire screen, etc.

**Comment by abartow** [comment]
Zooming out has always been limited. Zooming in is now also limited by https://github.com/ZackUhlenhuth/HostHelper/commit/68218d8499bd7c0ed343164fcabe4f14177b2c2e.

**Comment by ZackUhlenhuth** [comment]
There's something funky going on with the zoom right now. When you fix it make sure it works well (right now when I try to zoom out it looks like it get stuck zoomed out until I zoom out even more)

**Comment by jameshloving** [comment]
Appears fixed in 3f12060333e3dcdb6f254803b8f01f6e390980b1
