### ISSUE TITLE
Parties should be able to move tables

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#33]

**Comment by abartow** [comment]
What does this mean?

**Comment by jameshloving** [comment]
A party should be able to be moved from one table to another - unseated and reseated, e.g., they didn't like the table or friends show up.

**Comment by nickuhlenhuth** [comment]
Implemented with [4389be1](https://github.com/ZackUhlenhuth/HostHelper/commit/4389be1aa1a23790efb597cf7b9812197262cc41)
