### ISSUE TITLE
Reset button for view

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#4]
If you drag the restaurant diagram out of the viewable area, there's no way to get it back without refreshing the page.

**Comment by abartow** [comment]
I bounded the pan view to the map, so it should not longer be possible to drag the restaurant diagram out of the viewable area. Worst case, you can just zoom all the way out to reset. 

So I'm saying this is done as  of https://github.com/ZackUhlenhuth/HostHelper/commit/e1f5060a684802ac3af63f2a151d91e710006359
