### ISSUE TITLE
Upcoming list should sort by reservation time or ETA, NOT time of list entry creation

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#40]

**Comment by abartow** [comment]
https://github.com/ZackUhlenhuth/HostHelper/commit/b65bb07acd2a8104289dffc793ad8e4a7b09f20d does some stuff towards this. Will probably have to look at this more again after the whole split upcoming list thing is done, so I'll leave this issue open.

**Comment by abartow** [comment]
Should be done as of now.
