### ISSUE TITLE
Color scheme?

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#41]

**Comment by jameshloving** [comment]
https://bootswatch.com/slate/
![image](https://cloud.githubusercontent.com/assets/18295616/14924065/9a24caea-0e0e-11e6-9729-089f9c8452cc.png)

**Comment by abartow** [comment]
Work on this is ongoing on the dark-mode branch.

**Comment by abartow** [comment]
Done as of https://github.com/ZackUhlenhuth/HostHelper/commit/84e2f4942e098172d24d2aa7632a8d8cda0647ed
