### ISSUE TITLE
Cancel waitlist/reservation button should reset the form

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#42]

**Comment by ZackUhlenhuth** [comment]
pretty sure you can make this happen automatically by changing the button's type from submit to reset or something like that

**Comment by ZackUhlenhuth** [comment]
But then you'll need to put the current date and time

**Comment by jameshloving** [comment]
Should be fixed in ec7097ab3a850e582d1d92f2d31f1d70c3953a79
