### ISSUE TITLE
Clock incorrectly displays AM/PM label when time is 12:xx

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#49]

**Comment by nickuhlenhuth** [comment]
I use the get12Hours function for verifiying reservation times, so make sure that doesn't get messed up!

**Comment by abartow** [comment]
Should be fixed by https://github.com/ZackUhlenhuth/HostHelper/commit/9dbb4e7cc31fb1ddf839f0529548312bc0762147
