### ISSUE TITLE
There should be a way to override the reservation warning popup

### ISSUE THREAD

**Issue by abartow** [ZackUhlenhuth/HostHelper#53]
Based on the principle of user control, there should be a way to override the reservation warning popup.

**Comment by jameshloving** [comment]
And the seat capacity warning, too, if that hasn't been dealt with

We can just change alert() to confirm() and reword the prompts a bit

**Comment by jameshloving** [comment]
Added in 88fc3c39346e4a08934b53021d39a79379c338b8
