### ISSUE TITLE
Figure out why f1c7ad3a causes seating parties to no longer remove them from the waitlist.

### ISSUE THREAD

**Issue by abartow** [ZackUhlenhuth/HostHelper#54]
For some reason, f1c7ad3a98a918efbbe8690a9d22191f52736bfc causes parties to no longer be removed from the waitlist after they are seated. We need f1c7ad3a98a918efbbe8690a9d22191f52736bfc for aesthetic reasons, so we'll have to source down this bug.

**Comment by abartow** [comment]
... and now this bug appears to be on master. Wonderful.

**Comment by nickuhlenhuth** [comment]
Also, if you Delete an entry from the Upcoming list, it doesn't remove it anymore... definitely something to do with the Undo/Redo stuff @abartow

**Comment by abartow** [comment]
@nickuhlenhuth I found the commit that broke it and created issue #57 for that problem.

**Comment by abartow** [comment]
This should be fixed as of https://github.com/ZackUhlenhuth/HostHelper/commit/240ffd739c36a89552d05d1063cd2279a4eaea69
