### ISSUE TITLE
One of the recent commits broke the table suggestion algorithm

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#56]
![image](https://cloud.githubusercontent.com/assets/18295616/14995579/7d54b7ee-1143-11e6-8a22-4bc2cdabffbb.png)
The algorithm should NOT suggest a 6-top over a 4-top (or 5-top) for a party of 4...

**Comment by abartow** [comment]
Do you have a known-good commit where things worked? I'll do git bisect for you if you do.

**Comment by jameshloving** [comment]
Fixed in fb9151353773ba12192d8dde83379835c2b7c931
