### ISSUE TITLE
Hard to read text in Walk-in drop down

### ISSUE THREAD

**Issue by nickuhlenhuth** [ZackUhlenhuth/HostHelper#59]
@abartow

**Comment by abartow** [comment]
I'm more than willing to fix this, but do you have a screenshot? It looks pretty readable on my screen right now.

**Comment by nickuhlenhuth** [comment]
Light grey text on a white background:
![read](https://cloud.githubusercontent.com/assets/7707843/15004688/31383026-1188-11e6-991b-fcb7a2a59de4.JPG)

**Comment by abartow** [comment]
I'll look into it, but it seems like a web browser/platform thing to me. I don't see any CSS calling for it to be that color. This is what it looks like on Chrome. 

<img width="228" alt="screen shot 2016-05-03 at 11 41 00 pm" src="https://cloud.githubusercontent.com/assets/6297172/15004721/8b096a0c-1188-11e6-8368-1a5c4410324d.png">

**Comment by nickuhlenhuth** [comment]
That's strange. I'm also using Chrome

**Comment by abartow** [comment]
I am still looking at this. I have managed to duplicate this issue with Chrome in a Windows VM.

**Comment by abartow** [comment]
Aha! Found the bug. The slate.css style is overriding Chrome's UserAgent stylesheet and inheriting the text color from somewhere else, which on Windows is that really ugly grey. Fixed in https://github.com/ZackUhlenhuth/HostHelper/commit/ec72abfe38b45568df9ad3244c809e0a2844847c.
