### ISSUE TITLE
Multiple Undo functionality incorrect

### ISSUE THREAD

**Issue by ZackUhlenhuth** [ZackUhlenhuth/HostHelper#61]
Multiple undos seems to put back the same party multiple times, instead of the various different parties.

**Comment by abartow** [comment]
Are you sure you're not undoing and then redoing?

**Comment by ZackUhlenhuth** [comment]
Ya, I added everyone to a table, and then Sally
I undo multiple times
3 Sallys appear in the list

**Comment by ZackUhlenhuth** [comment]
Wait maybe you are right, it is possible I was hitting redo.
If this isn't the behavior for you feel free to close. I was using a Mac trackpad and it sucked

**Comment by ZackUhlenhuth** [comment]
Ya my mistake

**Comment by abartow** [comment]
No, that's actually really good feedback! We should probably do something to make the difference between the undo and redo buttons stand out more.

**Comment by ZackUhlenhuth** [comment]
okay, also can you do the Upcoming List / Future List combo issue too? I'll do it once I get back to my dorm but I'm really exhausted from this compilers project.
let me know
