### ISSUE TITLE
Edit & delete "Upcoming" parties

### ISSUE THREAD

**Issue by jameshloving** [ZackUhlenhuth/HostHelper#7]

**Comment by abartow** [comment]
How do we actually want to do this? Do we just want text boxes in place, or do we want a popup window, or...?

**Comment by jameshloving** [comment]
I was originally thinking a long press function, but that's about as
discoverable  as Narnia
On Apr 9, 2016 1:04 AM, "abartow" notifications@github.com wrote:

How do we actually want to do this? Do we just want text boxes in place, or
do we want a popup window, or...?

**Comment by abartow** [comment]
https://github.com/ZackUhlenhuth/HostHelper/commit/5ca30bc97c86693e561361dd7b8149e531e018cb adds support for editing everything as waitlist entries, but we still need to add support for changing reservation times.
